services:
  ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ros2
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
